server:
  port: 9292
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ZuulGateway
#Zuul实现路由转发的作用
zuul:
  routes: #路由
    weather: #随便命名
      path: /api/**
      service-id: study-business