spring:
  application:
    name: business-stu-sign
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.145:8848

dubbo:
  scan:
    base-packages: com.zzp.study.business.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.247.145:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
