server:
  port: 8787
  servlet:
    context-path: /sign

remote:
  server:
    address: 192.168.247.145
    nacos-port: 8848
    sentinel-port: 8088

spring:
  application:
    name: business-stu-sign
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${remote.server.address}:${remote.server.nacos-port}
    sentinel:
      transport:
        dashboard: ${remote.server.address}:${remote.server.sentinel-port}
      eager: true

dubbo:
  scan:
    base-packages: com.zzp.study.business.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${remote.server.address}:${remote.server.nacos-port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

